const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOOGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM_FROM_CART: "DELETE_ITEM_FROM_CART",
  DECREASE_ITEM: "DECREASE_ITEM",
};

export default CartActionTypes;
